spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: mongodb+srv://Rahul:Rahul123@fitness-microservice.vylrov5.mongodb.net/ai-service
      database: ai-service

server:
  port: 8083

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/
